<a href="https://colab.research.google.com/github/vinitakawale/Deep-Learning/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Implementing Sigmoid function with numpy - g(z) = 1 /1 + e^-x 

In [3]:
import math

def basic_sigmoid(x) :
  s = 1 + 1 + math.exp(-x)

  return s;



In [10]:
basic_sigmoid(3)   
# works on scalar only 
    

'\n    Compute sigmoid of x.\n\n    Arguments:\n    x -- A scalar\n\n    Return:\n    s -- sigmoid(x)\n    does not work on vectors [1,2,3,4]\n    '

In [13]:
# FOR VECTOR IMPLEMENTATION USE NUMPY 
import numpy as np
def sigmoid(x):
  s = 1 / (1 + np.exp(-x));
  return s;

In [14]:
sigmoid(np.array([1,2,3,4]))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [15]:
# Sigmoid gradient computation

def sigmoid_gradient(x) : 
   s = sigmoid(x);
   s = s * (1 - s);
   return s;

In [16]:
sigmoid_gradient(np.array([1,2,3,4]))

array([0.19661193, 0.10499359, 0.04517666, 0.01766271])

In [3]:
# Image to Vector
def imageToVector(image):

    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1);
    return v;

In [4]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(imageToVector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [9]:
# implement normalization to improve the performance to radient descent so it converges 
def normalizeRows(x):
  x_norm = np.linalg.norm(x,axis=1,keepdims=True);
  x = x/x_norm;
  return x


In [10]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [11]:
# implement softmax

def softmax(x):
  x_exp = np.exp(x);
  x_sum = np.sum(x_exp, axis=1, keepdims=True);
  s = x_exp / x_sum;
  return s;

# New Section

In [16]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


In [ ]:
from google.colab import drive
drive.mount('/content/drive')